TARGET = ./build/qshell/qshell.exe

HDRS_DIR = \
	include

SRC = \
	./src/main.cpp \
	./src/clear.cpp \
	./src/exit.cpp \
	./src/logo.cpp

.PHONY: all, build, clean

$(TARGET):
	g++ -I $(HDRS_DIR) $(SRC) -o $(TARGET)

all: clean build

build: $(TARGET)

clean:
	rm -rf $(TARGET)